---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# craigr: an R package to get data from craigslist

The purpose of this package is to obtain data from any section of
craigslist and load it into a clean `data.frame` within R.  Currently this only
works with apartment searches.  See the "Package status" below.

## Install

`devtools::install_github("adletaw/craigr")`

## Package status

This package is under active develpment.  Currently, you can download housing
rental data only for Seattle or Houston only.

## Usage

*craigr* will do an apartment search using the function `list_housing`.  You can
supply almost any search parameters that are available on craiglist.  

First you have to specify the location and area.  The location works as the 
Craigslist subdomain, e.g. [seattle.craigslist.org](https://seattle.craigslist.org)

The area allows you to filter to a more specific location according to the
pre-programmed options in Craigslist.  Using `all` will search the entire location
(in this case, the greater Seattle metro).

```{r location}
craigr::list_housing(location = "seattle", area = "all", max_results = 100)
```
